version: "3.9"

services:
  backend:
    build: ./backend-nest
    container_name: restaurant-backend
    ports:
      - "3002:3000"
    env_file:
      - ./backend-nest/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: restaurant-frontend
    ports:
      - "80:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: restaurant-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
